## Diet Recommendation System

In [32]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [33]:
df = pd.read_csv('static/Food__Nutrition__dataset/food.csv')

In [34]:
df.head(5)

,Category,Description,Nutrient Data Bank Number,Data.Alpha Carotene,Data.Ash,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,...,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - IU,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
0,BUTTER,"BUTTER,WITH SALT",1001,0,2.11,158,0,0.06,215,19,...,24,576,0.09,2499,684,0.17,0.003,0.0,2.32,7.0
1,BUTTER,"BUTTER,WHIPPED,WITH SALT",1002,0,2.11,158,0,0.06,219,19,...,26,827,0.05,2499,684,0.13,0.003,0.0,2.32,7.0
2,BUTTER OIL,"BUTTER OIL,ANHYDROUS",1003,0,0.00,193,0,0.00,256,22,...,5,2,0.01,3069,840,0.01,0.001,0.0,2.80,8.6
3,CHEESE,"CHEESE,BLUE",1004,0,5.11,74,0,2.34,75,15,...,256,1395,2.66,763,198,1.22,0.166,0.0,0.25,2.4
4,CHEESE,"CHEESE,BRICK",1005,0,3.18,76,0,2.79,94,15,...,136,560,2.60,1080,292,1.26,0.065,0.0,0.26,2.5

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7413 entries, 0 to 7412
Data columns (total 48 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Category                                                 7413 non-null   object
 1   Description                                              7413 non-null   object
 2   Nutrient Data Bank Number                                7413 non-null   int64
 3   Data.Alpha Carotene                                      7413 non-null   int64
 4   Data.Ash                                                 7413 non-null   float64
 5   Data.Beta Carotene                                       7413 non-null   int64
 6   Data.Beta Cryptoxanthin                                  7413 non-null   int64
 7   Data.Carbohydrate                                        7413 non-null   float64
 8   Data.Cholesterol                                         7413 non-null   int64
 9   Data.Choline                                             7413 non-null   int64
 10  Data.Fiber                                               7413 non-null   float64
 11  Data.Kilocalories                                        7413 non-null   int64
 12  Data.Lutein and Zeaxanthin                               7413 non-null   int64
 13  Data.Lycopene                                            7413 non-null   int64
 14  Data.Manganese                                           7413 non-null   float64
 15  Data.Niacin                                              7413 non-null   float64
 16  Data.Pantothenic Acid                                    7413 non-null   float64
 17  Data.Protein                                             7413 non-null   float64
 18  Data.Refuse Percentage                                   7413 non-null   int64
 19  Data.Retinol                                             7413 non-null   int64
 20  Data.Riboflavin                                          7413 non-null   float64
 21  Data.Selenium                                            7413 non-null   float64
 22  Data.Sugar Total                                         7413 non-null   float64
 23  Data.Thiamin                                             7413 non-null   float64
 24  Data.Water                                               7413 non-null   float64
 25  Data.Fat.Monosaturated Fat                               7413 non-null   float64
 26  Data.Fat.Polysaturated Fat                               7413 non-null   float64
 27  Data.Fat.Saturated Fat                                   7413 non-null   float64
 28  Data.Fat.Total Lipid                                     7413 non-null   float64
 29  Data.Household Weights.1st Household Weight              7413 non-null   float64
 30  Data.Household Weights.1st Household Weight Description  6943 non-null   object
 31  Data.Household Weights.2nd Household Weight              7413 non-null   int64
 32  Data.Household Weights.2nd Household Weight Description  4313 non-null   object
 33  Data.Major Minerals.Calcium                              7413 non-null   int64
 34  Data.Major Minerals.Copper                               7413 non-null   float64
 35  Data.Major Minerals.Iron                                 7413 non-null   float64
 36  Data.Major Minerals.Magnesium                            7413 non-null   int64
 37  Data.Major Minerals.Phosphorus                           7413 non-null   int64
 38  Data.Major Minerals.Potassium                            7413 non-null   int64
 39  Data.Major Minerals.Sodium                               7413 non-null   int64
 40  Data.Major Minerals.Zinc                                 7413 non-null   float64
 41  Data.Vitamins.Vitamin A - IU                             7413 non-null   int64
 42  Data.Vitamins.Vitamin A - RAE                            7413 non-null   int64
 43  Data.Vitamins.Vitamin B12                                7413 non-null   float64
 44  Data.Vitamins.Vitamin B6                                 7413 non-null   float64
 45  Data.Vitamins.Vitamin C                                  7413 non-null   float64
 46  Data.Vitamins.Vitamin E                                  7413 non-null   float64
 47  Data.Vitamins.Vitamin K                                  7413 non-null   float64
dtypes: float64(25), int64(19), object(4)
memory usage: 2.7+ MB

In [36]:
df.shape

(7413, 48)

In [37]:
df.columns

Index(['Category', 'Description', 'Nutrient Data Bank Number',
       'Data.Alpha Carotene', 'Data.Ash', 'Data.Beta Carotene',
       'Data.Beta Cryptoxanthin', 'Data.Carbohydrate', 'Data.Cholesterol',
       'Data.Choline', 'Data.Fiber', 'Data.Kilocalories',
       'Data.Lutein and Zeaxanthin', 'Data.Lycopene', 'Data.Manganese',
       'Data.Niacin', 'Data.Pantothenic Acid', 'Data.Protein',
       'Data.Refuse Percentage', 'Data.Retinol', 'Data.Riboflavin',
       'Data.Selenium', 'Data.Sugar Total', 'Data.Thiamin', 'Data.Water',
       'Data.Fat.Monosaturated Fat', 'Data.Fat.Polysaturated Fat',
       'Data.Fat.Saturated Fat', 'Data.Fat.Total Lipid',
       'Data.Household Weights.1st Household Weight',
       'Data.Household Weights.1st Household Weight Description',
       'Data.Household Weights.2nd Household Weight',
       'Data.Household Weights.2nd Household Weight Description',
       'Data.Major Minerals.Calcium', 'Data.Major Minerals.Copper',
       'Data.Major Minerals.Iron', 'Data.Major Minerals.Magnesium',
       'Data.Major Minerals.Phosphorus', 'Data.Major Minerals.Potassium',
       'Data.Major Minerals.Sodium', 'Data.Major Minerals.Zinc',
       'Data.Vitamins.Vitamin A - IU', 'Data.Vitamins.Vitamin A - RAE',
       'Data.Vitamins.Vitamin B12', 'Data.Vitamins.Vitamin B6',
       'Data.Vitamins.Vitamin C', 'Data.Vitamins.Vitamin E',
       'Data.Vitamins.Vitamin K'],
      dtype='object')

## Data Preprocessing

In [38]:
# Checking the Missing Values
df.isnull().sum()

Category                                                      0
Description                                                   0
Nutrient Data Bank Number                                     0
Data.Alpha Carotene                                           0
Data.Ash                                                      0
Data.Beta Carotene                                            0
Data.Beta Cryptoxanthin                                       0
Data.Carbohydrate                                             0
Data.Cholesterol                                              0
Data.Choline                                                  0
Data.Fiber                                                    0
Data.Kilocalories                                             0
Data.Lutein and Zeaxanthin                                    0
Data.Lycopene                                                 0
Data.Manganese                                                0
Data.Niacin                                                   0
Data.Pantothenic Acid                                         0
Data.Protein                                                  0
Data.Refuse Percentage                                        0
Data.Retinol                                                  0
Data.Riboflavin                                               0
Data.Selenium                                                 0
Data.Sugar Total                                              0
Data.Thiamin                                                  0
Data.Water                                                    0
Data.Fat.Monosaturated Fat                                    0
Data.Fat.Polysaturated Fat                                    0
Data.Fat.Saturated Fat                                        0
Data.Fat.Total Lipid                                          0
Data.Household Weights.1st Household Weight                   0
Data.Household Weights.1st Household Weight Description     470
Data.Household Weights.2nd Household Weight                   0
Data.Household Weights.2nd Household Weight Description    3100
Data.Major Minerals.Calcium                                   0
Data.Major Minerals.Copper                                    0
Data.Major Minerals.Iron                                      0
Data.Major Minerals.Magnesium                                 0
Data.Major Minerals.Phosphorus                                0
Data.Major Minerals.Potassium                                 0
Data.Major Minerals.Sodium                                    0
Data.Major Minerals.Zinc                                      0
Data.Vitamins.Vitamin A - IU                                  0
Data.Vitamins.Vitamin A - RAE                                 0
Data.Vitamins.Vitamin B12                                     0
Data.Vitamins.Vitamin B6                                      0
Data.Vitamins.Vitamin C                                       0
Data.Vitamins.Vitamin E                                       0
Data.Vitamins.Vitamin K                                       0
dtype: int64

In [39]:
# Data.Household Weights.1st Household Weight Description,Data.Household Weights.2nd Household Weight Description --Missing values

In [40]:
# checking duplicate values
df.duplicated().sum()

np.int64(0)

In [41]:
# List of columns to drop
columns_to_drop = [
    'Data.Household Weights.1st Household Weight Description', 
    'Data.Household Weights.2nd Household Weight Description',
    'Data.Household Weights.1st Household Weight',
    'Data.Household Weights.2nd Household Weight'
]

# Drop the columns
data = df.drop(columns=columns_to_drop)

In [42]:
data.isnull().sum()

Category                          0
Description                       0
Nutrient Data Bank Number         0
Data.Alpha Carotene               0
Data.Ash                          0
Data.Beta Carotene                0
Data.Beta Cryptoxanthin           0
Data.Carbohydrate                 0
Data.Cholesterol                  0
Data.Choline                      0
Data.Fiber                        0
Data.Kilocalories                 0
Data.Lutein and Zeaxanthin        0
Data.Lycopene                     0
Data.Manganese                    0
Data.Niacin                       0
Data.Pantothenic Acid             0
Data.Protein                      0
Data.Refuse Percentage            0
Data.Retinol                      0
Data.Riboflavin                   0
Data.Selenium                     0
Data.Sugar Total                  0
Data.Thiamin                      0
Data.Water                        0
Data.Fat.Monosaturated Fat        0
Data.Fat.Polysaturated Fat        0
Data.Fat.Saturated Fat            0
Data.Fat.Total Lipid              0
Data.Major Minerals.Calcium       0
Data.Major Minerals.Copper        0
Data.Major Minerals.Iron          0
Data.Major Minerals.Magnesium     0
Data.Major Minerals.Phosphorus    0
Data.Major Minerals.Potassium     0
Data.Major Minerals.Sodium        0
Data.Major Minerals.Zinc          0
Data.Vitamins.Vitamin A - IU      0
Data.Vitamins.Vitamin A - RAE     0
Data.Vitamins.Vitamin B12         0
Data.Vitamins.Vitamin B6          0
Data.Vitamins.Vitamin C           0
Data.Vitamins.Vitamin E           0
Data.Vitamins.Vitamin K           0
dtype: int64

## Getting Insights From Data

In [43]:
data.describe(exclude='object')

,Nutrient Data Bank Number,Data.Alpha Carotene,Data.Ash,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,Data.Fiber,Data.Kilocalories,...,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - IU,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
count,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,...,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000
mean,14116.443680,21.210711,1.852459,159.043437,8.776744,21.785381,37.162822,20.673546,1.993147,219.655875,...,268.348172,331.590719,1.875125,767.568191,99.437070,1.172903,0.269547,9.075651,0.842837,9.448604
std,8767.416214,269.714183,2.993228,1126.285026,154.184860,27.123491,119.738438,45.481990,4.292873,171.668713,...,404.916220,977.046544,4.193682,3871.307652,761.653061,4.512816,0.565116,63.443284,4.169756,66.067619
min,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8121.000000,0.000000,0.830000,0.000000,0.000000,0.490000,0.000000,0.000000,0.000000,82.000000,...,103.000000,31.000000,0.190000,0.000000,0.000000,0.000000,0.030000,0.000000,0.000000,0.000000
50%,12539.000000,0.000000,1.240000,0.000000,0.000000,9.290000,2.000000,0.000000,0.300000,181.000000,...,210.000000,86.000000,0.770000,33.000000,0.000000,0.010000,0.110000,0.000000,0.050000,0.000000
75%,18424.000000,0.000000,2.200000,1.000000,0.000000,30.590000,60.000000,20.000000,2.300000,331.000000,...,328.000000,428.000000,2.460000,280.000000,24.000000,0.830000,0.330000,3.500000,0.390000,1.700000
max,93600.000000,14251.000000,99.800000,42891.000000,7923.000000,100.000000,3100.000000,1388.000000,79.000000,902.000000,...,16500.000000,38758.000000,181.610000,100000.000000,30000.000000,98.890000,12.000000,2400.000000,149.400000,1714.500000

In [44]:
data.describe(include='object')

       Category           Description
count      7413                  7413
unique     1183                  7409
top        BEEF  BABYFOOD,MEAT,BF,STR
freq        457                     2

In [48]:
from sklearn.cluster import KMeans
import numpy as np

# Select relevant features for clustering (excluding non-numeric columns)
features = data.select_dtypes(include=['float64', 'int64'])

# Choose the number of clusters
num_clusters = 5  # You can adjust this number based on your needs
kmeans = KMeans(n_clusters=num_clusters)

# Fit the model
kmeans.fit(features)

# Assign cluster labels back to the original dataframe
data['Cluster'] = kmeans.labels_

ValueError: Input X contains NaN.
KMeans does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values