## Diet Recommendation System

In [35]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.cluster import KMeans
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [36]:
df = pd.read_csv('static/Food__Nutrition__dataset/food.csv')

In [37]:
df.head(5)

,Category,Description,Nutrient Data Bank Number,Data.Alpha Carotene,Data.Ash,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,...,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - IU,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
0,BUTTER,"BUTTER,WITH SALT",1001,0,2.11,158,0,0.06,215,19,...,24,576,0.09,2499,684,0.17,0.003,0.0,2.32,7.0
1,BUTTER,"BUTTER,WHIPPED,WITH SALT",1002,0,2.11,158,0,0.06,219,19,...,26,827,0.05,2499,684,0.13,0.003,0.0,2.32,7.0
2,BUTTER OIL,"BUTTER OIL,ANHYDROUS",1003,0,0.00,193,0,0.00,256,22,...,5,2,0.01,3069,840,0.01,0.001,0.0,2.80,8.6
3,CHEESE,"CHEESE,BLUE",1004,0,5.11,74,0,2.34,75,15,...,256,1395,2.66,763,198,1.22,0.166,0.0,0.25,2.4
4,CHEESE,"CHEESE,BRICK",1005,0,3.18,76,0,2.79,94,15,...,136,560,2.60,1080,292,1.26,0.065,0.0,0.26,2.5

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7413 entries, 0 to 7412
Data columns (total 48 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Category                                                 7413 non-null   object
 1   Description                                              7413 non-null   object
 2   Nutrient Data Bank Number                                7413 non-null   int64
 3   Data.Alpha Carotene                                      7413 non-null   int64
 4   Data.Ash                                                 7413 non-null   float64
 5   Data.Beta Carotene                                       7413 non-null   int64
 6   Data.Beta Cryptoxanthin                                  7413 non-null   int64
 7   Data.Carbohydrate                                        7413 non-null   float64
 8   Data.Cholesterol                                         7413 non-null   int64
 9   Data.Choline                                             7413 non-null   int64
 10  Data.Fiber                                               7413 non-null   float64
 11  Data.Kilocalories                                        7413 non-null   int64
 12  Data.Lutein and Zeaxanthin                               7413 non-null   int64
 13  Data.Lycopene                                            7413 non-null   int64
 14  Data.Manganese                                           7413 non-null   float64
 15  Data.Niacin                                              7413 non-null   float64
 16  Data.Pantothenic Acid                                    7413 non-null   float64
 17  Data.Protein                                             7413 non-null   float64
 18  Data.Refuse Percentage                                   7413 non-null   int64
 19  Data.Retinol                                             7413 non-null   int64
 20  Data.Riboflavin                                          7413 non-null   float64
 21  Data.Selenium                                            7413 non-null   float64
 22  Data.Sugar Total                                         7413 non-null   float64
 23  Data.Thiamin                                             7413 non-null   float64
 24  Data.Water                                               7413 non-null   float64
 25  Data.Fat.Monosaturated Fat                               7413 non-null   float64
 26  Data.Fat.Polysaturated Fat                               7413 non-null   float64
 27  Data.Fat.Saturated Fat                                   7413 non-null   float64
 28  Data.Fat.Total Lipid                                     7413 non-null   float64
 29  Data.Household Weights.1st Household Weight              7413 non-null   float64
 30  Data.Household Weights.1st Household Weight Description  6943 non-null   object
 31  Data.Household Weights.2nd Household Weight              7413 non-null   int64
 32  Data.Household Weights.2nd Household Weight Description  4313 non-null   object
 33  Data.Major Minerals.Calcium                              7413 non-null   int64
 34  Data.Major Minerals.Copper                               7413 non-null   float64
 35  Data.Major Minerals.Iron                                 7413 non-null   float64
 36  Data.Major Minerals.Magnesium                            7413 non-null   int64
 37  Data.Major Minerals.Phosphorus                           7413 non-null   int64
 38  Data.Major Minerals.Potassium                            7413 non-null   int64
 39  Data.Major Minerals.Sodium                               7413 non-null   int64
 40  Data.Major Minerals.Zinc                                 7413 non-null   float64
 41  Data.Vitamins.Vitamin A - IU                             7413 non-null   int64
 42  Data.Vitamins.Vitamin A - RAE                            7413 non-null   int64
 43  Data.Vitamins.Vitamin B12                                7413 non-null   float64
 44  Data.Vitamins.Vitamin B6                                 7413 non-null   float64
 45  Data.Vitamins.Vitamin C                                  7413 non-null   float64
 46  Data.Vitamins.Vitamin E                                  7413 non-null   float64
 47  Data.Vitamins.Vitamin K                                  7413 non-null   float64
dtypes: float64(25), int64(19), object(4)
memory usage: 2.7+ MB

In [39]:
df.shape

(7413, 48)

In [40]:
df.columns

Index(['Category', 'Description', 'Nutrient Data Bank Number',
       'Data.Alpha Carotene', 'Data.Ash', 'Data.Beta Carotene',
       'Data.Beta Cryptoxanthin', 'Data.Carbohydrate', 'Data.Cholesterol',
       'Data.Choline', 'Data.Fiber', 'Data.Kilocalories',
       'Data.Lutein and Zeaxanthin', 'Data.Lycopene', 'Data.Manganese',
       'Data.Niacin', 'Data.Pantothenic Acid', 'Data.Protein',
       'Data.Refuse Percentage', 'Data.Retinol', 'Data.Riboflavin',
       'Data.Selenium', 'Data.Sugar Total', 'Data.Thiamin', 'Data.Water',
       'Data.Fat.Monosaturated Fat', 'Data.Fat.Polysaturated Fat',
       'Data.Fat.Saturated Fat', 'Data.Fat.Total Lipid',
       'Data.Household Weights.1st Household Weight',
       'Data.Household Weights.1st Household Weight Description',
       'Data.Household Weights.2nd Household Weight',
       'Data.Household Weights.2nd Household Weight Description',
       'Data.Major Minerals.Calcium', 'Data.Major Minerals.Copper',
       'Data.Major Minerals.Iron', 'Data.Major Minerals.Magnesium',
       'Data.Major Minerals.Phosphorus', 'Data.Major Minerals.Potassium',
       'Data.Major Minerals.Sodium', 'Data.Major Minerals.Zinc',
       'Data.Vitamins.Vitamin A - IU', 'Data.Vitamins.Vitamin A - RAE',
       'Data.Vitamins.Vitamin B12', 'Data.Vitamins.Vitamin B6',
       'Data.Vitamins.Vitamin C', 'Data.Vitamins.Vitamin E',
       'Data.Vitamins.Vitamin K'],
      dtype='object')

## Data Preprocessing

In [41]:
# Checking the Missing Values
df.isnull().sum()

Category                                                      0
Description                                                   0
Nutrient Data Bank Number                                     0
Data.Alpha Carotene                                           0
Data.Ash                                                      0
Data.Beta Carotene                                            0
Data.Beta Cryptoxanthin                                       0
Data.Carbohydrate                                             0
Data.Cholesterol                                              0
Data.Choline                                                  0
Data.Fiber                                                    0
Data.Kilocalories                                             0
Data.Lutein and Zeaxanthin                                    0
Data.Lycopene                                                 0
Data.Manganese                                                0
Data.Niacin                                                   0
Data.Pantothenic Acid                                         0
Data.Protein                                                  0
Data.Refuse Percentage                                        0
Data.Retinol                                                  0
Data.Riboflavin                                               0
Data.Selenium                                                 0
Data.Sugar Total                                              0
Data.Thiamin                                                  0
Data.Water                                                    0
Data.Fat.Monosaturated Fat                                    0
Data.Fat.Polysaturated Fat                                    0
Data.Fat.Saturated Fat                                        0
Data.Fat.Total Lipid                                          0
Data.Household Weights.1st Household Weight                   0
Data.Household Weights.1st Household Weight Description     470
Data.Household Weights.2nd Household Weight                   0
Data.Household Weights.2nd Household Weight Description    3100
Data.Major Minerals.Calcium                                   0
Data.Major Minerals.Copper                                    0
Data.Major Minerals.Iron                                      0
Data.Major Minerals.Magnesium                                 0
Data.Major Minerals.Phosphorus                                0
Data.Major Minerals.Potassium                                 0
Data.Major Minerals.Sodium                                    0
Data.Major Minerals.Zinc                                      0
Data.Vitamins.Vitamin A - IU                                  0
Data.Vitamins.Vitamin A - RAE                                 0
Data.Vitamins.Vitamin B12                                     0
Data.Vitamins.Vitamin B6                                      0
Data.Vitamins.Vitamin C                                       0
Data.Vitamins.Vitamin E                                       0
Data.Vitamins.Vitamin K                                       0
dtype: int64

In [42]:
# Data.Household Weights.1st Household Weight Description,Data.Household Weights.2nd Household Weight Description --Missing values

In [43]:
# checking duplicate values
df.duplicated().sum()

np.int64(0)

In [44]:
# List of columns to drop
columns_to_drop = [
    'Data.Household Weights.1st Household Weight Description', 
    'Data.Household Weights.2nd Household Weight Description',
    'Data.Household Weights.1st Household Weight',
    'Data.Household Weights.2nd Household Weight',
    'Nutrient Data Bank Number'
]

# Drop the columns
df_cleaned = df.drop(columns=columns_to_drop)
# Save as CSV
df_cleaned.to_csv('df_cleaned.csv', index=False)

In [45]:
df_cleaned.isnull().sum()

Category                          0
Description                       0
Data.Alpha Carotene               0
Data.Ash                          0
Data.Beta Carotene                0
Data.Beta Cryptoxanthin           0
Data.Carbohydrate                 0
Data.Cholesterol                  0
Data.Choline                      0
Data.Fiber                        0
Data.Kilocalories                 0
Data.Lutein and Zeaxanthin        0
Data.Lycopene                     0
Data.Manganese                    0
Data.Niacin                       0
Data.Pantothenic Acid             0
Data.Protein                      0
Data.Refuse Percentage            0
Data.Retinol                      0
Data.Riboflavin                   0
Data.Selenium                     0
Data.Sugar Total                  0
Data.Thiamin                      0
Data.Water                        0
Data.Fat.Monosaturated Fat        0
Data.Fat.Polysaturated Fat        0
Data.Fat.Saturated Fat            0
Data.Fat.Total Lipid              0
Data.Major Minerals.Calcium       0
Data.Major Minerals.Copper        0
Data.Major Minerals.Iron          0
Data.Major Minerals.Magnesium     0
Data.Major Minerals.Phosphorus    0
Data.Major Minerals.Potassium     0
Data.Major Minerals.Sodium        0
Data.Major Minerals.Zinc          0
Data.Vitamins.Vitamin A - IU      0
Data.Vitamins.Vitamin A - RAE     0
Data.Vitamins.Vitamin B12         0
Data.Vitamins.Vitamin B6          0
Data.Vitamins.Vitamin C           0
Data.Vitamins.Vitamin E           0
Data.Vitamins.Vitamin K           0
dtype: int64

## Getting Insights From Data

In [46]:
df_cleaned.describe(exclude='object')

,Data.Alpha Carotene,Data.Ash,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,Data.Fiber,Data.Kilocalories,Data.Lutein and Zeaxanthin,...,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - IU,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
count,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,...,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000,7413.000000
mean,21.210711,1.852459,159.043437,8.776744,21.785381,37.162822,20.673546,1.993147,219.655875,127.406178,...,268.348172,331.590719,1.875125,767.568191,99.437070,1.172903,0.269547,9.075651,0.842837,9.448604
std,269.714183,2.993228,1126.285026,154.184860,27.123491,119.738438,45.481990,4.292873,171.668713,1029.635386,...,404.916220,977.046544,4.193682,3871.307652,761.653061,4.512816,0.565116,63.443284,4.169756,66.067619
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.830000,0.000000,0.000000,0.490000,0.000000,0.000000,0.000000,82.000000,0.000000,...,103.000000,31.000000,0.190000,0.000000,0.000000,0.000000,0.030000,0.000000,0.000000,0.000000
50%,0.000000,1.240000,0.000000,0.000000,9.290000,2.000000,0.000000,0.300000,181.000000,0.000000,...,210.000000,86.000000,0.770000,33.000000,0.000000,0.010000,0.110000,0.000000,0.050000,0.000000
75%,0.000000,2.200000,1.000000,0.000000,30.590000,60.000000,20.000000,2.300000,331.000000,0.000000,...,328.000000,428.000000,2.460000,280.000000,24.000000,0.830000,0.330000,3.500000,0.390000,1.700000
max,14251.000000,99.800000,42891.000000,7923.000000,100.000000,3100.000000,1388.000000,79.000000,902.000000,39550.000000,...,16500.000000,38758.000000,181.610000,100000.000000,30000.000000,98.890000,12.000000,2400.000000,149.400000,1714.500000

In [47]:
df_cleaned.tail(100)

,Category,Description,Data.Alpha Carotene,Data.Ash,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,Data.Fiber,...,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - IU,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
7313,QUAIL,"QUAIL,COOKED,TOTAL EDIBLE",0,0.80,0,0,0.0,86,66,0.0,...,216,52,3.10,234,70,0.36,0.62,2.3,0.70,4.2
7314,PHEASANT,"PHEASANT,CKD,TOTAL EDIBLE",0,1.30,0,0,0.0,89,86,0.0,...,271,43,1.37,190,57,0.72,0.75,2.3,0.27,4.9
7315,EGGS,"EGGS,SCRMBLD,FRZ MIXTURE",0,1.10,246,0,7.5,65,193,0.0,...,147,162,0.14,410,21,0.17,0.01,0.0,0.84,1.8
7316,DOVE,"DOVE,CKD (INCL SQUAB)",0,1.10,0,0,0.0,116,64,0.0,...,256,57,3.83,95,28,0.41,0.57,2.9,0.06,4.0
7317,PORK,"PORK,ORIENTAL STYLE,DEHYD",0,2.60,0,0,1.4,67,0,0.0,...,139,685,1.15,0,0,0.30,0.20,0.0,0.36,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7408,FROG LEGS,"FROG LEGS,RAW",0,1.40,0,0,0.0,50,65,0.0,...,285,58,1.00,50,15,0.40,0.12,0.0,1.00,0.1
7409,MACKEREL,"MACKEREL,SALTED",0,13.40,0,0,0.0,95,95,0.0,...,520,4450,1.10,157,47,12.00,0.41,0.0,2.38,7.8
7410,SCALLOP,"SCALLOP,(BAY&SEA),CKD,STMD",0,3.06,0,0,0.0,53,81,0.0,...,476,265,3.00,100,30,1.30,0.10,0.0,1.50,0.2
7411,SNAIL,"SNAIL,RAW",0,1.30,0,0,2.0,50,65,0.0,...,382,70,1.00,100,30,0.50,0.13,0.0,5.00,0.1
7412,TURTLE,"TURTLE,GREEN,RAW",0,1.20,0,0,0.0,50,65,0.0,...,230,68,1.00,100,30,1.00,0.12,0.0,0.50,0.1

In [48]:
df_cleaned.columns

Index(['Category', 'Description', 'Data.Alpha Carotene', 'Data.Ash',
       'Data.Beta Carotene', 'Data.Beta Cryptoxanthin', 'Data.Carbohydrate',
       'Data.Cholesterol', 'Data.Choline', 'Data.Fiber', 'Data.Kilocalories',
       'Data.Lutein and Zeaxanthin', 'Data.Lycopene', 'Data.Manganese',
       'Data.Niacin', 'Data.Pantothenic Acid', 'Data.Protein',
       'Data.Refuse Percentage', 'Data.Retinol', 'Data.Riboflavin',
       'Data.Selenium', 'Data.Sugar Total', 'Data.Thiamin', 'Data.Water',
       'Data.Fat.Monosaturated Fat', 'Data.Fat.Polysaturated Fat',
       'Data.Fat.Saturated Fat', 'Data.Fat.Total Lipid',
       'Data.Major Minerals.Calcium', 'Data.Major Minerals.Copper',
       'Data.Major Minerals.Iron', 'Data.Major Minerals.Magnesium',
       'Data.Major Minerals.Phosphorus', 'Data.Major Minerals.Potassium',
       'Data.Major Minerals.Sodium', 'Data.Major Minerals.Zinc',
       'Data.Vitamins.Vitamin A - IU', 'Data.Vitamins.Vitamin A - RAE',
       'Data.Vitamins.Vitamin B12', 'Data.Vitamins.Vitamin B6',
       'Data.Vitamins.Vitamin C', 'Data.Vitamins.Vitamin E',
       'Data.Vitamins.Vitamin K'],
      dtype='object')

In [49]:
# from sklearn.manifold import TSNE

# # Step 3: Dimensionality Reduction using t-SNE
# tsne = TSNE(n_components=2, random_state=90)
# X_tsne = tsne.fit_transform(X_scaled)

# # Step 4: Create a DataFrame for plotting
# df_tsne = pd.DataFrame(data=X_tsne, columns=['TSNE1', 'TSNE2'])
# df_tsne['Cluster'] = df_filtered['Cluster']

# # Step 5: Visualize the clusters using t-SNE
# plt.figure(figsize=(10, 8))
# sns.scatterplot(data=df_tsne, x='TSNE1', y='TSNE2', hue='Cluster', palette='viridis', s=100, alpha=0.7)
# plt.title('Visualising the Clusters for recommendation ')
# plt.xlabel('t-SNE Component 1')
# plt.ylabel('t-SNE Component 2')
# plt.legend(title='cluster_mapping')
# plt.grid(True)
# plt.show()

In [50]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import numpy as np

# Assume df_cleaned is your cleaned DataFrame
df_filtered = df_cleaned.copy()

# Step 1: Identify numeric columns for scaling
nutritional_columns = df_filtered.select_dtypes(include=['float64', 'int64']).columns  # Only numeric columns

# Step 2: Feature Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_filtered[nutritional_columns])

# Step 3: K-Means Clustering
kmeans = KMeans(n_clusters=10, random_state=90)
df_filtered['Cluster'] = kmeans.fit_predict(X_scaled)

# Step 4: Define mappings for user goals
goal_mapping = {
    "maintain weight": 0,
    "muscle gain": 1,
    "fat burn with lean muscle retention": 2,
    "enhance athletic performance": 3,
    "improve immunity": 4,
    "bone and joint health": 5,
    "gut health": 6,
    "mental wellness": 7,
    "energy boost": 8,
    "recovery from illness/surgery": 9
}

# Function to recommend foods based on user input
def recommend_diet(user_goal, user_activity):
    # Step 5: Check user goal mapping
    user_goal = user_goal.strip().lower()
    if user_goal not in goal_mapping:
        print("Invalid goal specified.")
        return

    # Get the cluster number based on user goal
    goal_cluster = goal_mapping[user_goal]

    # Step 6: Filter dataset based on user goal
    recommended_foods = df_filtered[df_filtered['Cluster'] == goal_cluster]

    # Step 7: Randomize and select a few recommendations
    if not recommended_foods.empty:
        # Randomly select a subset of recommendations (e.g., 5)
        random_recommendations = recommended_foods.sample(n=min(5, len(recommended_foods)), random_state=1)

        # Step 8: Display recommendations
        print("Recommended Foods based on your inputs:")
        # Displaying relevant information
        print(random_recommendations[['Category', 'Description', 'Data.Protein', 'Data.Kilocalories']])
    else:
        print("No recommendations available based on your preferences.")

# Example user input
user_goal = "enhance athletic performance"  # Example user goal
user_activity = "Moderately Active"  # Example user activity level (not used in this logic)

# Call the recommendation function
recommend_diet(user_goal, user_activity)

Recommended Foods based on your inputs:
     Category                                        Description  \
5094     LAMB                               LAMB,GROUND,CKD,BRLD
7078   WALRUS                    WALRUS,MEAT,RAW (ALASKA NATIVE)
4448     CLAM                      CLAM,MXD SP,CKD,BREADED&FRIED
2755     PORK  PORK,CURED,HAM W/ NAT JUICES,WHL,BNLESS,LN & F...
799   CHICKEN   CHICKEN,BROILERS OR FRYERS,LEG,MEAT&SKN,CKD,STWD

      Data.Protein  Data.Kilocalories
5094         24.75                283
7078         19.20                199
4448         14.24                202
2755         19.38                112
799          24.17                220

In [51]:
import pickle

# Assuming kmeans is your trained KMeans model and scaler is your StandardScaler
with open('kmeans_model.pkl', 'wb') as f:
    pickle.dump(kmeans, f)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)